# Generated by Django 6.0.3 on 2026-03-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(unique=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rain', models.FloatField()),
                ('radiation', models.FloatField()),
            ],
        ),
    ]
