# Generated by Django 6.0.3 on 2026-03-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHPWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(choices=[('C1', 'Độ ẩm đất'), ('C2', 'Lượng mưa'), ('C3', 'Bốc thoát hơi nước ET₀'), ('C4', 'Nhiệt độ'), ('C5', 'Độ ẩm không khí'), ('C6', 'Nắng/gió mùa khô')], max_length=2, unique=True)),
                ('weight', models.FloatField(verbose_name='Trọng số')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trọng số AHP',
                'verbose_name_plural': 'Trọng số AHP',
            },
        ),
        migrations.CreateModel(
            name='IrrigationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_time', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(verbose_name='Nhiệt độ hiện tại')),
                ('humidity', models.FloatField(verbose_name='Độ ẩm hiện tại')),
                ('rain', models.FloatField(verbose_name='Lượng mưa')),
                ('soil_moisture', models.FloatField(verbose_name='Độ ẩm đất')),
                ('et0', models.FloatField(verbose_name='ET₀')),
                ('recommended_action', models.CharField(max_length=20, verbose_name='Hành động khuyến nghị')),
                ('score_pa1', models.FloatField(blank=True, null=True)),
                ('score_pa2', models.FloatField(blank=True, null=True)),
                ('score_pa3', models.FloatField(blank=True, null=True)),
                ('score_pa4', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='et0',
            field=models.FloatField(blank=True, null=True, verbose_name='Bốc thoát hơi nước (mm/ngày)'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='soil_moisture',
            field=models.FloatField(blank=True, null=True, verbose_name='Độ ẩm đất (%)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.FloatField(verbose_name='Độ ẩm không khí (%)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='radiation',
            field=models.FloatField(verbose_name='Bức xạ (MJ/m²)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='rain',
            field=models.FloatField(verbose_name='Lượng mưa (mm)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.FloatField(verbose_name='Nhiệt độ (°C)'),
        ),
        migrations.CreateModel(
            name='AlternativeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.CharField(choices=[('PA1', 'Phương án 1'), ('PA2', 'Phương án 2'), ('PA3', 'Phương án 3'), ('PA4', 'Phương án 4')], max_length=3)),
                ('criterion', models.CharField(choices=[('C1', 'Độ ẩm đất'), ('C2', 'Lượng mưa'), ('C3', 'Bốc thoát hơi nước ET₀'), ('C4', 'Nhiệt độ'), ('C5', 'Độ ẩm không khí'), ('C6', 'Nắng/gió mùa khô')], max_length=2)),
                ('score', models.FloatField(verbose_name='Điểm số')),
            ],
            options={
                'verbose_name': 'Điểm phương án',
                'verbose_name_plural': 'Điểm các phương án',
                'unique_together': {('alternative', 'criterion')},
            },
        ),
    ]
