# Generated by Django 5.2.6 on 2026-03-27 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0003_alter_ahpweights_id_alter_alternativescore_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên vườn')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
                ('area', models.FloatField(default=1.0, verbose_name='Diện tích (ha)')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Khu vực')),
            ],
        ),
        migrations.CreateModel(
            name='GardenRealtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField(verbose_name='Nhiệt độ (°C)')),
                ('humidity', models.FloatField(verbose_name='Độ ẩm không khí (%)')),
                ('rain', models.FloatField(verbose_name='Lượng mưa (mm)')),
                ('radiation', models.FloatField(verbose_name='Bức xạ (MJ/m²)')),
                ('et0', models.FloatField(default=0, verbose_name='Bốc thoát hơi nước (mm/ngày)')),
                ('soil_moisture', models.FloatField(default=0, verbose_name='Độ ẩm đất')),
                ('ai_score', models.FloatField(default=0, verbose_name='Độ tin cậy AI')),
                ('ai_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Khuyến nghị AI')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_data', to='irrigation.garden')),
            ],
        ),
    ]
